### ISSUE TITLE
摘要生成完之后，报错显示生成文件夹里没有fig.png

### ISSUE THREAD

**Issue by overal-well-off-society** [CCCBora/auto-draft#16]
abstract part has been generated. 
>>USAGE>> For generating abstract, 6081 tokens have been used (5453 for prompts; 628 for completion). 33277 tokens have been used in total.
================POST-PROCESSING================
Traceback (most recent call last):
  File "/home/dk/Downloads/auto-draft-main/auto_backgrounds.py", line 302, in <module>
    output = generate_draft(target_title, knowledge_database="ml_textbook_test")
  File "/home/dk/Downloads/auto-draft-main/auto_backgrounds.py", line 280, in generate_draft
    create_copies(destination_folder)
  File "/home/dk/Downloads/auto-draft-main/utils/tex_processing.py", line 57, in create_copies
    shutil.copy2(original_fig, target_fig)
  File "/home/dk/anaconda3/envs/autopaper/lib/python3.9/shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/dk/anaconda3/envs/autopaper/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/outputs_20230704_220432/fig.png'

Process finished with exit code 1

**Comment by overal-well-off-society** [comment]
请问图片是在哪一步生成的呢，我看代码里有断注释：
# def figures_generation(paper, save_to_path, model):
#     # todo: this function is not complete.
#     prompts = generate_experiments_prompts(paper)
#     gpt_response, usage = get_responses(prompts, model)
#     list_of_methods = list(extract_json(gpt_response))
#     generate_random_figures(list_of_methods, os.path.join(save_to_path, "comparison.png"))
#     return usage

**Comment by CCCBora** [comment]
> abstract part has been generated.
> 
> > > USAGE>> For generating abstract, 6081 tokens have been used (5453 for prompts; 628 for completion). 33277 tokens have been used in total.
> > > ================POST-PROCESSING================
> > > Traceback (most recent call last):
> > > File "/home/dk/Downloads/auto-draft-main/auto_backgrounds.py", line 302, in 
> > > output = generate_draft(target_title, knowledge_database="ml_textbook_test")
> > > File "/home/dk/Downloads/auto-draft-main/auto_backgrounds.py", line 280, in generate_draft
> > > create_copies(destination_folder)
> > > File "/home/dk/Downloads/auto-draft-main/utils/tex_processing.py", line 57, in create_copies
> > > shutil.copy2(original_fig, target_fig)
> > > File "/home/dk/anaconda3/envs/autopaper/lib/python3.9/shutil.py", line 444, in copy2
> > > copyfile(src, dst, follow_symlinks=follow_symlinks)
> > > File "/home/dk/anaconda3/envs/autopaper/lib/python3.9/shutil.py", line 264, in copyfile
> > > with open(src, 'rb') as fsrc:
> > > FileNotFoundError: [Errno 2] No such file or directory: 'outputs/outputs_20230704_220432/fig.png'
> 
> Process finished with exit code 1

噢这个问题是因为我有一个模板里忘记放入fig.png导致的。我现在没有做生成图片的功能，只放了一个空的图片。
我会在下一个更新中修复这个问题。

**Comment by CCCBora** [comment]
> 请问图片是在哪一步生成的呢，我看代码里有断注释：
> 
> # def figures_generation(paper, save_to_path, model):
> # # todo: this function is not complete.
> # prompts = generate_experiments_prompts(paper)
> # gpt_response, usage = get_responses(prompts, model)
> # list_of_methods = list(extract_json(gpt_response))
> # generate_random_figures(list_of_methods, os.path.join(save_to_path, "comparison.png"))
> # return usage

这个功能还没有实现。 目前是复制一个现成的空图片fig.png。这个函数只是随机画几条线
